name: projectoverwatch
description: Generarte name for a Start Up company
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

# #docregion dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  english_words: ^3.1.0
# #enddocregion dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.4.0

flutter:
  uses-material-design: true


